spring:
  zipkin:    #服务追踪
    base-url: http://192.168.159.129:9411 #zipkin服务器地址
    discovery-client-enabled: false #关闭服务发现,否则SpringCloud会把zipkin的url当做服务名称
    sender:
      type: web #设置使用web的方式传送数据
    sleuth:
      sampler:
        probability: 1 #设置抽样采集率为100%,默认0.1即10%


