spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.159.129:3306/gulimall_oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-order

  thymeleaf:
    cache: false

#    rabbitmq:
  rabbitmq:
    host: 192.168.159.129
    port: 5672
    virtual-host: /
    #开启发送端确认  发送给消息代理服务器broker
    publisher-confirms: true
    #开启发送端消息抵达队列的确认
    publisher-returns: true
    #只要抵达队列，以异步发送优先回调我们这个returnconfirm
    template:
      mandatory: true
    #消费端手动ack消息，开启手动确认模式
    listener:
      simple:
        acknowledge-mode: manual

#springsession配置
  session:
    store-type: redis

  redis:
    host: 192.168.159.129
    port: 6379
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss



mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 9000

#线程池配置
gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10


#配置自定义的支付宝配置参数
alipay:
  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjVUID2pRnkomhW21IB+LD0oQEmlLfJ74+Bjxqh7xCpTRq/X24mZKK6J9K2lT9xhxbnmgp2eTRtVuYcTI78G02RS5pinpHLDDZaq8afhOfEEwOmTB22ttEf6elNwssbT2Yi//qgyQNTMmy5HcRIPDF+L7bMwZzestwcjXnUaIZa4uYRpAij8sehHPiK120U8AVvWn+niL13s6pLZ3WFzBOaqVkpDLcSAxHquTo6CgTd8CB2CTlSnemXnBt8eFtdCzxuXk6S1Yuu72d3HAiPGgdgVd5CciDZ3RT6/P6gZSSJAaNyTVWqHzXoBN1Y6cSS0wBTacvb+SXFZGv86zclNdfQIDAQAB
  app-id: 2016102600762819
  merchant-private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCvUAFQwYY+aswM5/EwhRfpM3gmI1yCtzPnPrRv4DDNEPKKqWSceafEj94v/ndFEw88mtVdx6JdyzYQen+K4KUK4PQEJzM7iJ58x9uqZmu2yuq2OKzzZ2ACMiWYtr7jDSmfZg/RnZPfYSVcSl4nVViTxjebJfGrxE7NLW5vG85W8RwJsRkzrqIANMShM8IFaLENJINmMjvRBiRknKABn9J8SDtlMuP6HTn36u0mwuuyzheggfYVlIxuLK0Hvd4otl82AQCUGLXIvd+qmhWWLjHykJuIe+hvQZOXvlER/hg19BsgsB8kCtwgurmbjYDgNnwt0f3Lfx60gI3rlMb9VqG1AgMBAAECggEAelbUdCx4p/oTJzZ846UdSIm4YLTwi++Y8tiZRjEnHROkjgsjwOZMoyjanpdvV+6zBVHvb6AuuFFlCx7Q/nNB+VN+NZ+9auAt6Vn2+vS6WjdEj6EBYGJVZ3LjNazhjMTUtP2eMGNMm+fJEJx9E+nFBGqgx041Ve6KJzh7BmJbHePARicBuetibFDsu1qoeIQSX6OwQCKnrZf/HozvD48G1JyPqSptk8XV9Iuk8xeLEBzGHIgfWhte50tHNyFuDxmd5DEg1lZqqy/LQwVVM6gJ9B5juuu2O0J72Hk8bk2HN1rZRJSx1zkBAsPZVEKhPY/T2Zg/c+ial48a1Yc3rQe8yQKBgQDUBZb2fGzL1nr0rw7TBPYqWnk3YAE3EiXECNpcsRYqlo4+JopsTfYNZq12zwWRQVX9yH6soCMbFwwylAxfUaieB8j3F9GbPnCgBQGO60p+u9ZFrJfTrDUudtcWeymaY2pQtC3hdzdig78lJBVYPkCT4VTYqPoer0LEvfaB2MWskwKBgQDTrSRbg9TfPnOlcouMrd5l2lgvQ8hBUkBktdW7yHiaefQ5mXYssoEEUY2RCgJCOuHk4iHIgvDCgGnkttaficZ4KqzuaEax7G+gYTk7QzQ6pu9mvsDGueMC8QbRCy6DuoB5DKItqp2rdJXzHCxH1/5irSt4bRFfoFdJR/AT4fgtlwKBgBuzBz/4jXYr9TBWVod3FHoAC+oSHtaFBm4QAgcuE4lI1hiEjH0NymGB0pO9BCsv7/4R3YrL+Qom/q707JDfaDoNJlIxyG6Rv8EIJmX3k2nvPFUp8UP0MZZ6bCtBt/O1nUQh5gSYwKGcOLKvfiJjL6iiPaV4ngS4PO7bKoNYQKsFAoGAdZBxY/6JSWBXPKmsxfp/TdSCK+Yan+T97LFtPvltumZHdYI9N0ABFhPxa3/Cl2Q6uDO8DbBj5bMKnUPLWhpcR7t0BomV0hX+PXYiIj8GEBlNV6RUT0tIwQZ7AbmTIQiBeDnDDVf4cBS1f6vDEDfvioChZyY0gwb707CHr5NOkosCgYEAx4gTrNHllKuBlGBSLeB64OPvxZSXbuCXlqrkKLSitdGHMH0Zu+7uQfDhSMSwEHNa1Jo7uGONf/cyTr5krxrWH/SsNceT5CIgIJgrySkXbf5X+xVT1I8Cjb3hb7ZXNHtBPFmyhy862TeFgeMaHOloJW4el7TxUSPXENiHOHXFs8E=
  notify-url: http://q740km4v.xiaomy.net/payed/notify #该地址必须外网可访问，因为是支付宝给我们发信息(这里使用的是内网穿透)
  return-url: http://member.gulimall.com/memberOrder.html
  sign-type: RSA2
  charset: utf-8
  gateway-url: https://openapi.alipaydev.com/gateway.do
  timeout-express: 30m
