spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.159.129:3306/gulimall_oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-order


#    rabbitmq:
  rabbitmq:
    host: 192.168.159.129
    port: 5672
    virtual-host: /
    #开启发送端确认  发送给消息代理服务器broker
    publisher-confirms: true
    #开启发送端消息抵达队列的确认
    publisher-returns: true
    #只要抵达队列，以异步发送优先回调我们这个returnconfirm
    template:
      mandatory: true
    #消费端手动ack消息，开启手动确认模式
    listener:
      simple:
        acknowledge-mode: manual

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 9000
