spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI4GAmNKXWh84DsJoMZWny
      secret-key: QrCvUCvJuboUkIdUDH2lWiv707VwMR
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: gulimall-yuke

      sms:
        app-code: 4f7292af19c348a38840e47b5b504d36
        path: /sms/send
        host: https://smssend.shumaidata.com


  application:
    name: gulimall-third-party

server:
  port: 30000
